export const FETCH_DATA_REQUESTED = 'FETCH_DATA_REQUESTED';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_FILTER_REQUESTED = 'FETCH_FILTER_REQUESTED';
export const FETCH_FILTER_SUCCESS = 'FETCH_FILTER_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const SELECT_FILTER_VALUE = 'SELECT_FILTER_VALUE';
